### ISSUE TITLE
Yuvarlak çerçeve?

### ISSUE THREAD

**Issue by doganyuncu** [salimcansatici/Instagram-Real-Time-Profile-Photo-Update-Bot#3]
peki profil fotoğrafına yuvarlak çerçeve nasıl ekleyeceğiz? onu da gelecek güncellemeden verir misiniz? :)

**Comment by salimcansatici** [comment]
Merhaba,

Resmin üzerine eklenen yuvarlak çerçeveden bahsediyorsunuz sanırım. Şimdilik akılda bir şeyler oluşması ve geliştirilebilecek bir program ortaya sundum eğer kimse el atmaz ise iş başa düşer ve istediğiniz özelliği de 1-2 hafta içerisinde programımıza getirebilirim 👍
