### ISSUE TITLE
chrome versiyon farkı

### ISSUE THREAD

**Issue by fullautomatic** [salimcansatici/Instagram-Real-Time-Profile-Photo-Update-Bot#4]
chrome versiyonu seleniumda ki gibi mi sistemde 80.02 varsa 80.02 de mi çalışıyor?

**Comment by salimcansatici** [comment]
Merhaba,

Soruna yönelik daha detaylı bir soru yöneltirsen sana bilgilendirme konusunda yardımcı olacağım.

Sevgiler,
