### ISSUE TITLE
selenium ile yapacakmısınız?

### ISSUE THREAD

**Issue by fullautomatic** [salimcansatici/Instagram-Real-Time-Profile-Photo-Update-Bot#5]
bu işlemleri c# selenium ile yapabilirmisiniz?

**Comment by salimcansatici** [comment]
Merhaba,

C# Selenium ile de aynı şekilde adımlar izlenerek yapılabilir fakat c# ile aynı şeyleri yazmak ya da geliştirmek istemiyorum. Fikir olarak gayet açık yazmaya çalıştım kodlarla çok haşır neşir olmayan birisinin anlayacağı düzeyde her şeyi basit tutmaya çalıştım. İlgili projeyi kodlarken kodlamaya dair pek bir şey bilmeyen insanların anlamasına yönelik kodladım. Performans artışı ya da kusursuz hata senaryolarının koşullandırılması gibi bir işleyişe odaklanmadım. 

Bilginize,
