### ISSUE TITLE
No Usable Sandbox! Update Your Kernel --no-sandbox

### ISSUE THREAD

**Issue by GokseLW** [salimcansatici/Instagram-Real-Time-Profile-Photo-Update-Bot#7]
![image](https://user-images.githubusercontent.com/57256097/83384118-41857d00-a3ef-11ea-98da-11e9fcf674a7.png)

**Comment by salimcansatici** [comment]
Merhaba,

Görmemişim fakat yine de çözümü aktarayım. Args olarak --no-sandbox etiketini koymanız gerekmekte.

Teşekkürler,
