### ISSUE TITLE
Upload Limiti

### ISSUE THREAD

**Issue by EMREOYUN** [salimcansatici/Instagram-Real-Time-Profile-Photo-Update-Bot#8]
Hocam kod 30-40 resimden sonra upload yapmıyor. Muhtemelen instagram yeni uploadları engelliyor. 
Up hızı 5sn.

**Comment by salimcansatici** [comment]
Merhaba,

Maalesef Instagram bu konuda bir çok API'yı engellediği gibi manuel işlemleri de engelledi bundan dolayı artık bu gibi işlemler bir süre profil fotoğrafı değiştirme engeli koymakta. Upload hızı minimum 60 saniye olarak denemenizi öneriyorum. 

Teşekkürler,
Salimcan Satıcı

**Comment by EMREOYUN** [comment]
> Merhaba,
> 
> Maalesef Instagram bu konuda bir çok API'yı engellediği gibi manuel işlemleri de engelledi bundan dolayı artık bu gibi işlemler bir süre profil fotoğrafı değiştirme engeli koymakta. Upload hızı minimum 60 saniye olarak denemenizi öneriyorum.
> 
> Teşekkürler,
> Salimcan Satıcı

Upload'ı her 6 saate bir ayarladım. Gayet güzel çalışıyor.

**Comment by EMREOYUN** [comment]
Closed #8
