### ISSUE TITLE
Yüksek İşlemcı Kullanımı

### ISSUE THREAD

**Issue by EMREOYUN** [salimcansatici/Instagram-Real-Time-Profile-Photo-Update-Bot#9]
Umarım hala buralara bakıyorsundur. Program node.js üzerinden(chrome üzerinden değil) çok yüksek işlemci kullanıyor ve bu cihazdaki diğer uygulamaları etkiliyor. Bunu nasıl engelleyebiliriz?

**Comment by salimcansatici** [comment]
Merhaba,

Maalesef NodeJS ile kullanmış olduğunuz bu tür otomasyon işlemleri genellikle işlemciyi çok kullanır. NodeJS + Puppeteer entegrasyonlarında deneyimlediğime göre CPU'nun bir an önce kendisine verilmiş görevi bitirmek için kapasitesinin çoğunu/hepsini kullanır bu yüksek CPU kullanımı ile sonuçlanır. CPU kullanım sabitlemeyi bilmiyorum ama muhakkak vardır fakat bu performans yine de işlemci tipine ve çekirdek sayısına göre de değişmekte. i5 6500 işlemcim ile bir sorun yaşamadığımı söylemem gerek bu sorunu e7200 işlemcimde yaşamıştım.

Belli saniyede tekrarlattığın bir işlem var ise ****sayfa yüklenmesini hızlandırabilirsin** bu bir nebze CPU kullanımını dolaylı olarak rahatlatabilir**. Özellikle canvas içeren sayfalar felaket bir duruma sokabiliyor. Görev yöneticisini açıp gerçekten açmış olduğun kadar nodejs projesi olduğuna dikkat et bazen kapatıyorsun ama kapanmayabiliyor bir döngüye giriyor. 

Örneğin Args olarak ; 
`'--no-sandbox','--disable-setuid-sandbox', '--disable-accelerated-2d-canvas','--disable-canvas-aa', '--disable-2d-canvas-clip-aa'` 
bunları kullanabilirsin bunlar sayfanın daha hızlı açılmasını CPU'nun daha az sürede işlemi tamamlamasını sağlayabilir. Buna ek olarak ziyaret gerçekleştirdiğin siteden css ve js kodlarını yüklememeyi yazabilirsin kısa bir kodu vardır :) Bulabileceğine inanıyorum

**Comment by EMREOYUN** [comment]
Kullandığım cihazda Intel Xeon işlemci var 4 çekirdekli ve çekirdeklerin birini %100 kullanıyor. Aynı işlemi i3 bilgisayarımda da denedim ve yine 1 çekirdeği %100 kullanıyor.

>Belli saniyede tekrarlattığın bir işlem var ise *sayfa yüklenmesinihızlandırabilirsin bu bir nebze CPU kullanımını dolaylı olarak rahatlatabilir*.
Bunu anlamadım. Daha detaylı açıklayabilir misiniz?
>Görev yöneticisini açıp gerçekten açmış olduğun kadar nodejs projesiolduğuna dikkat et bazen kapatıyorsun ama kapanmayabiliyor bir döngüyegiriyor.
Bunu detaylı olarak takip ediyorum, sorunu da zaten oradan buldum.

Argları zaten ekledim belki işe yarar diye, Chromium'daki işlemciyi iyi bir nebze azalttı ama Node.js'i azaltamadı.

**Comment by salimcansatici** [comment]
> Bunu anlamadım. Daha detaylı açıklayabilir misiniz?
> Görev yöneticisini açıp gerçekten açmış olduğun kadar nodejs projesiolduğuna dikkat et bazen kapatıyorsun ama kapanmayabiliyor bir döngüyegiriyor.
> Bunu detaylı olarak takip ediyorum, sorunu da zaten oradan buldum. Argları zaten ekledim belki işe yarar diye, Chromium'daki işlemciyi iyi bir nebze azalttı ama Node.js'i azaltamadı. 


Bu noktada yaptığınız işlemin tam olarak ne olduğunu ne yaptığınızı yazmanız daha yerinde olacaktır bende size buna göre konuyla alakalı yönlendirme sağlayayım. Sadece Puppeteer mi çalıştırıyorsunuz? Arkaplanda neler oluyor? Kısaca üstün körü yaptığınız işlem nedir?

**Comment by EMREOYUN** [comment]
> > Bunu anlamadım. Daha detaylı açıklayabilir misiniz?
> > Görev yöneticisini açıp gerçekten açmış olduğun kadar nodejs projesiolduğuna dikkat et bazen kapatıyorsun ama kapanmayabiliyor bir döngüyegiriyor.
> > Bunu detaylı olarak takip ediyorum, sorunu da zaten oradan buldum. Argları zaten ekledim belki işe yarar diye, Chromium'daki işlemciyi iyi bir nebze azalttı ama Node.js'i azaltamadı.
> 
> Bu noktada yaptığınız işlemin tam olarak ne olduğunu ne yaptığınızı yazmanız daha yerinde olacaktır bende size buna göre konuyla alakalı yönlendirme sağlayayım. Sadece Puppeteer mi çalıştırıyorsunuz? Arkaplanda neler oluyor? Kısaca üstün körü yaptığınız işlem nedir?

Sizin verdiğiniz kodun aynısı çalışıyor, sadece blocking wait değeri 6 saate ayarlı

**Comment by salimcansatici** [comment]
Güncelleme+

e7200 işlemcime kıyasla 6500 işlemcim daha akıcı ve sorunsuz çalıyordu. Şimdi 6500 işlemcime kıyasla 5900x işlemcim daha akıcı ve sıkıntısız çalışmakta. Puppeteer tarafından browser ayağa kaldırıldığından işlemci ve ram önemli.

**Comment by EMREOYUN** [comment]
> Güncelleme+
> 
> e7200 işlemcime kıyasla 6500 işlemcim daha akıcı ve sorunsuz çalıyordu. Şimdi 6500 işlemcime kıyasla 5900x işlemcim daha akıcı ve sıkıntısız çalışmakta. Puppeteer tarafından browser ayağa kaldırıldığından işlemci ve ram önemli.

Tahminimce çekirdek bazlı, birkaç cihazda denedim ve her seferinde tek bir çekirdeği %100 güçte çalıştırıyor. Kullandığım cihazda 4 çekirdek olduğu için direk %25 harcıyordu toplamda. Teşekkürler yardımlarınız için.
